=== pgolovkin/vlsu-lab2-xml/src/complex/flatDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT flat (address, rooms, owner, author)>
   <!ATTLIST flat video ENTITY #REQUIRED>
   <!ATTLIST address flat ID #REQUIRED>
   <!ENTITY % address "(street, house)">
   <!ELEMENT address (%address;)>     
         <!ELEMENT street (#PCDATA)>
         <!ELEMENT house (#PCDATA)>
   <!ELEMENT rooms (room+)>
      <!ATTLIST room roomType (Ванная|Гостинная|Кухонка|Спальня|Прочее|ТуалетО_О) "Прочее">
      <!ELEMENT room (#PCDATA|area|width|height|length)>
         <!ELEMENT area (#PCDATA)>
         <!ELEMENT width (#PCDATA)>
         <!ELEMENT height (#PCDATA)>
         <!ELEMENT length (#PCDATA)>
   <!ELEMENT owner (firstName, lastName, ownerAddress)>
      <!ATTLIST ownerAddress flat IDREF #REQUIRED>
      <!ATTLIST owner photo ENTITY #REQUIRED>
      <!ELEMENT firstName (#PCDATA)>
      <!ELEMENT lastName (#PCDATA)>
      <!ELEMENT ownerAddress (%address;)>
   <!ELEMENT author (#PCDATA)>
   
<!ENTITY test "Test!">

<!ENTITY photoFile SYSTEM "/img.gif" NDATA GIF>
<!NOTATION GIF SYSTEM "gif viwer">

<!ENTITY videoFile SYSTEM "/video.wmv" NDATA WMV>
<!NOTATION WMV SYSTEM "C:\Program Files\Windows Media Player\wmplayer.exe">

=== pgolovkin/vlsu-lab2-xml/src/complex/flat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE flat SYSTEM "flatDTD.dtd">
<flat video = "videoFile">
   <address flat = "кв.47">
      <street>
         Ул. П. Осипенко
      </street>
      <house>
         дом 14/43
      </house>
   </address>
   <rooms>
      <room roomType="Ванная">
         <area>
             23
         </area>
         <width>
             12
         </width>
         <height>
             23
         </height>
         <length>
             33
         </length>
      </room>
      <room>
         хороша комнатка
      </room>
   </rooms>   
   <owner photo = "photoFile">
      <firstName>
         Головкин
      </firstName>
      <lastName>
         Павел
      </lastName>
      <ownerAddress flat = "кв.47">
         <street>
            ул. П. Осипенко
         </street>
         <house>
            дом 14/43
         </house>
      </ownerAddress>
   </owner>
   <author>
      &test;
   </author>
</flat>
